version: "2" # zmiana wersji z 3 na 2
           services:
             db:
               image: mysql
               environment:
                 - MYSQL_ROOT_PASSWORD=pass123 # hasło na początku
                 - MYSQL_DATABASE=sma
                 - MYSQL_USER=mysql
                 - MYSQL_PASSWORD=pass123
               ports:
                 - 3306:3306
               command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
             app:
               build:
                 context: .
               ports:
                 - 8080:8080
                 - 9990:9990
               depends_on:
                 - db
               links: # dodany links/ dlaczego ? a dlaczego nie bridge ?
                 - db
               dns: 8.8.8.8
